services:
  - type: web
    name: bbj-church-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "8080"
      - key: JDBC_DATABASE_URL
        value: mysql://nrMPj1ECajN3NtY.root:LSTkYzHVTdplnF2X@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/bbj
      - key: JDBC_DATABASE_USERNAME
        value: nrMPj1ECajN3NtY.root
      - key: JDBC_DATABASE_PASSWORD
        value: LSTkYzHVTdplnF2X
      - key: B2_KEY_ID
        value: 0055be753f9e33f0000000001
      - key: B2_KEY_NAME
        value: Project
      - key: B2_BUCKET_NAME
        value: bbj1532

  - type: static
    name: bbj-church-frontend
    region: oregon
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://bbjdigital-e62a.onrender.com/api
